version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    ports:
      - "5434:5432"
    networks:
      - my-network

  nodejs-app:
    build: .
    container_name: DealService
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge