apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 9200
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
      restartPolicy: Always
