apiVersion: v1
kind: Service
metadata:
  name: nodejs-nodejs-app
spec:
  selector:
    app: nodejs-nodejs-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002 # Дозволяємо підлючення за межами кластера
  type: NodePort # Вмикаємо підлючення за межами кластера