apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30001 # Дозволяємо підлючення за межами кластера
  type: NodePort # Вмикаємо підлючення за межами кластера
